version: '3.7'

services:

  db:
    image: postgres:16-alpine
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: