version: '3.7'

services:

  db:
    image: postgres:16-alpine
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - db_test:/var/lib/postgresql/data

  app_test:
    build:
      context: .
      dockerfile: test.Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    command: h wait_for.sh db:5432 -- make tests

volumes:
  db_test:
