version: '3.7'

services:

  db:
    restart: always
    image: postgres:16-alpine
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - db_prod:/var/lib/postgresql/data

  web:
    env_file:
      - .env.prod
    build: .
    ports:
      - "5000:8001"
    depends_on:
      - cache
      - postgres
    command: >
      sh -c 
      "gunicorn src.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker -b 0.0.0.0:8001"


  proxy:
    restart: always
    build:
      context: ./proxy
    ports:
      - "8081:80"
    depends_on:
      - app

volumes:
  db_prod:
